package com.mycompany.casospoliciales;
// Generated 05-abr-2018 16:59:44 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * CasoPolicial generated by hbm2java
 */
public class CasoPolicial  implements java.io.Serializable {


     private String codcaso;
     private String nombre;
     private Date fechaInicio;
     private Date fechaFin;

    public CasoPolicial() {
    }

	
    public CasoPolicial(String codcaso) {
        this.codcaso = codcaso;
    }
    public CasoPolicial(String codcaso, String nombre, Date fechaInicio, Date fechaFin) {
       this.codcaso = codcaso;
       this.nombre = nombre;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
    }
   
    public String getCodcaso() {
        return this.codcaso;
    }
    
    public void setCodcaso(String codcaso) {
        this.codcaso = codcaso;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }




}


